version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    ports:
      - "5050:5050"
    dns:
      - "8.8.8.8"
    environment:
      PORT: 5050
      HOST: ""
      POSTGRES_URL: "postgres://admin:admin@postgres:5432/chat?sslmode=disable"
      CASSANDRA_URL: "cassandra"
      CORS_ALLOWED_HEADERS: "Content-Type,X-Requested-With,Origin,Authorization"
      CORS_ALLOWED_METHODS: "GET,HEAD,POST,PUT,OPTIONS"
      CORS_ALLOWED_ORIGINS: "*"
      JWT_SECRET_KEY: "__super.secret.key.123__"
      JWT_ISSUER: "mop.bucket"
      JWT_EXPIRES_IN_MINUTES: "3600"
    volumes:
      - ./api:/app
      - modules:/go
    depends_on:
      - postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    environment:
      BASE_URL: "/static"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: admin
      POSTGRES_PASS: admin

  #cassandra-1:
  #  image: cassandra:3.11.3
  #  ports:
  #    - "9042:9042"
  #  volumes:
  #    - cassandra-data:/var/lib/cassandra

  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra:3.11.3
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients

  cassandra-node-1:
    image: cassandra:3.11.3
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
    depends_on:
      - "cassandra-seed"


volumes:
  pg-data:
  cassandra-data:
  modules:
