version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      HOST: ""
      POSTGRES_URL: "postgres://admin:admin@postgres:5432/chat?sslmode=disable"
      CORS_ALLOWED_HEADERS: "Content-Type,X-Requested-With,Origin"
      CORS_ALLOWED_METHODS: "GET,HEAD,POST,PUT,OPTIONS"
      CORS_ALLOWED_ORIGINS: "*"
      JWT_SECRET_KEY: "__super.secret.key.123__"
    volumes:
      - ./api:/go/src/app
    depends_on:
      - postgres

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: admin
      POSTGRES_PASS: admin

volumes:
  pg-data:
    external: false
